# Generated by Django 4.0.5 on 2022-06-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_alter_book_pages_alter_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='modarg',
            field=models.CharField(default='Place', max_length=250),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.CharField(blank=True, choices=[('أقتصاد', 'eco'), ('أنتاج حيوانى', 'anp'), ('ألبان', 'alban'), ('حشرات', 'hasharat'), ('حيوان زراعى', 'anagr'), ('فاكهة', 'vig'), ('خضر', 'vig2'), ('زينة', 'zena'), ('أراضى', 'arady'), ('كيمياء حيوية', 'cimical')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('جارى المناقشة', 'جارى المناقشة'), ('تم المناقشة', 'تم المناقشة')], default='avalilable', max_length=50, null=True),
        ),
    ]
