# Generated by Django 4.0.5 on 2022-06-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0005_book_modarg_alter_book_pages_alter_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='datetime',
            field=models.DateTimeField(default='قبل المناقشة بأسبوع على الاقل'),
        ),
    ]
