# Generated by Django 4.0.5 on 2022-06-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0007_alter_book_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='datetime',
            field=models.DateTimeField(default='YYYY-MM-DD HH:MM'),
        ),
    ]
