# Generated by Django 4.0.5 on 2022-06-30 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0011_remove_book_datetime_book_datebook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='datebook',
            new_name='date',
        ),
    ]
