# Generated by Django 4.0.5 on 2022-06-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0014_remove_book_datebook_book_thidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.CharField(blank=True, choices=[('أقتصاد', 'أقتصاد'), ('أنتاج حيوانى', 'انتاج حيوانى'), ('ألبان', 'ألبان'), ('حشرات', 'حشرات'), ('حيوان زراعى', 'حيوان زراعى'), ('فاكهة', 'قاكهة'), ('خضر', 'خضر'), ('زينة', 'زينة'), ('أراضى', 'أراضى'), ('كيمياء حيوية', 'كيمياء حيوية')], max_length=50, null=True),
        ),
    ]
