# Generated by Django 4.0.5 on 2022-06-30 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0015_dept_status_alter_book_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='deptn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lms_app.dept'),
        ),
        migrations.AddField(
            model_name='book',
            name='statusn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lms_app.status'),
        ),
    ]
