# Generated by Django 4.0.5 on 2022-06-30 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0016_book_deptn_book_statusn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='Deptn',
        ),
        migrations.RenameModel(
            old_name='Dept',
            new_name='Statusn',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='statusn',
            new_name='deptnew',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='deptn',
            new_name='statusnew',
        ),
    ]
