# Generated by Django 4.0.5 on 2022-06-30 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0018_rename_statusn_dept_rename_deptn_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lms_app.dept'),
        ),
        migrations.AddField(
            model_name='book',
            name='stat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lms_app.status'),
        ),
    ]
