# Generated by Django 4.0.5 on 2022-06-30 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0019_book_depart_book_stat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
    ]
