# Generated by Django 4.0.5 on 2022-06-30 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0020_remove_book_pages_remove_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='action',
        ),
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.RemoveField(
            model_name='book',
            name='retal_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='retal_price_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='total_retal',
        ),
    ]
